# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SubnetCalculator.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(717, 430)
        MainWindow.setFocusPolicy(QtCore.Qt.StrongFocus)
        MainWindow.setAutoFillBackground(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBoxNWInfo = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBoxNWInfo.setGeometry(QtCore.QRect(10, 10, 311, 121))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.groupBoxNWInfo.setFont(font)
        self.groupBoxNWInfo.setObjectName("groupBoxNWInfo")
        self.layoutWidget = QtWidgets.QWidget(self.groupBoxNWInfo)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 20, 281, 81))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.labelNWAddress = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.labelNWAddress.setFont(font)
        self.labelNWAddress.setObjectName("labelNWAddress")
        self.gridLayout.addWidget(self.labelNWAddress, 0, 0, 1, 1)
        self.lineEditNWAddress = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEditNWAddress.setObjectName("lineEditNWAddress")
        self.gridLayout.addWidget(self.lineEditNWAddress, 0, 1, 1, 1)
        self.labelNumHost = QtWidgets.QLabel(self.layoutWidget)
        self.labelNumHost.setObjectName("labelNumHost")
        self.gridLayout.addWidget(self.labelNumHost, 1, 0, 1, 1)
        self.lineEditNumHost = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEditNumHost.setObjectName("lineEditNumHost")
        self.gridLayout.addWidget(self.lineEditNumHost, 1, 1, 1, 1)
        self.labelSbSize = QtWidgets.QLabel(self.layoutWidget)
        self.labelSbSize.setObjectName("labelSbSize")
        self.gridLayout.addWidget(self.labelSbSize, 2, 0, 1, 1)
        self.lineEditSbSize = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEditSbSize.setFocusPolicy(QtCore.Qt.TabFocus)
        self.lineEditSbSize.setFrame(True)
        self.lineEditSbSize.setReadOnly(True)
        self.lineEditSbSize.setObjectName("lineEditSbSize")
        self.gridLayout.addWidget(self.lineEditSbSize, 2, 1, 1, 1)
        self.groupBoxIPRange = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBoxIPRange.setGeometry(QtCore.QRect(10, 140, 311, 261))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.groupBoxIPRange.setFont(font)
        self.groupBoxIPRange.setObjectName("groupBoxIPRange")
        self.listWidgetIPRange = QtWidgets.QListWidget(self.groupBoxIPRange)
        self.listWidgetIPRange.setGeometry(QtCore.QRect(10, 20, 281, 221))
        self.listWidgetIPRange.setObjectName("listWidgetIPRange")
        self.groupBoxAddressInfo = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBoxAddressInfo.setGeometry(QtCore.QRect(330, 10, 371, 151))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.groupBoxAddressInfo.setFont(font)
        self.groupBoxAddressInfo.setObjectName("groupBoxAddressInfo")
        self.layoutWidget1 = QtWidgets.QWidget(self.groupBoxAddressInfo)
        self.layoutWidget1.setGeometry(QtCore.QRect(20, 20, 341, 111))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.labelDecimalOctets = QtWidgets.QLabel(self.layoutWidget1)
        self.labelDecimalOctets.setObjectName("labelDecimalOctets")
        self.gridLayout_2.addWidget(self.labelDecimalOctets, 0, 0, 1, 1)
        self.lineEditDecimalOctets = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEditDecimalOctets.setReadOnly(True)
        self.lineEditDecimalOctets.setObjectName("lineEditDecimalOctets")
        self.gridLayout_2.addWidget(self.lineEditDecimalOctets, 0, 1, 1, 1)
        self.labelDecimalAddress = QtWidgets.QLabel(self.layoutWidget1)
        self.labelDecimalAddress.setObjectName("labelDecimalAddress")
        self.gridLayout_2.addWidget(self.labelDecimalAddress, 1, 0, 1, 1)
        self.lineEditDecimalAddress = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEditDecimalAddress.setReadOnly(True)
        self.lineEditDecimalAddress.setObjectName("lineEditDecimalAddress")
        self.gridLayout_2.addWidget(self.lineEditDecimalAddress, 1, 1, 1, 1)
        self.labelBinaryOctets = QtWidgets.QLabel(self.layoutWidget1)
        self.labelBinaryOctets.setObjectName("labelBinaryOctets")
        self.gridLayout_2.addWidget(self.labelBinaryOctets, 2, 0, 1, 1)
        self.lineEditBinaryOctets = QtWidgets.QLineEdit(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.lineEditBinaryOctets.setFont(font)
        self.lineEditBinaryOctets.setReadOnly(True)
        self.lineEditBinaryOctets.setObjectName("lineEditBinaryOctets")
        self.gridLayout_2.addWidget(self.lineEditBinaryOctets, 2, 1, 1, 1)
        self.labelHexOctets = QtWidgets.QLabel(self.layoutWidget1)
        self.labelHexOctets.setObjectName("labelHexOctets")
        self.gridLayout_2.addWidget(self.labelHexOctets, 3, 0, 1, 1)
        self.lineEditHexOctets = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEditHexOctets.setReadOnly(True)
        self.lineEditHexOctets.setObjectName("lineEditHexOctets")
        self.gridLayout_2.addWidget(self.lineEditHexOctets, 3, 1, 1, 1)
        self.groupBoxNetmask = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBoxNetmask.setGeometry(QtCore.QRect(340, 170, 361, 181))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.groupBoxNetmask.setFont(font)
        self.groupBoxNetmask.setObjectName("groupBoxNetmask")
        self.labelNumSubnet = QtWidgets.QLabel(self.groupBoxNetmask)
        self.labelNumSubnet.setGeometry(QtCore.QRect(21, 144, 77, 16))
        self.labelNumSubnet.setObjectName("labelNumSubnet")
        self.lineEditNumSubnet = QtWidgets.QLineEdit(self.groupBoxNetmask)
        self.lineEditNumSubnet.setGeometry(QtCore.QRect(124, 144, 61, 22))
        self.lineEditNumSubnet.setReadOnly(True)
        self.lineEditNumSubnet.setObjectName("lineEditNumSubnet")
        self.labelNWClass = QtWidgets.QLabel(self.groupBoxNetmask)
        self.labelNWClass.setGeometry(QtCore.QRect(21, 24, 92, 16))
        self.labelNWClass.setObjectName("labelNWClass")
        self.lineEditIPAddress = QtWidgets.QLineEdit(self.groupBoxNetmask)
        self.lineEditIPAddress.setGeometry(QtCore.QRect(124, 54, 81, 22))
        self.lineEditIPAddress.setReadOnly(True)
        self.lineEditIPAddress.setObjectName("lineEditIPAddress")
        self.labelIPAddress = QtWidgets.QLabel(self.groupBoxNetmask)
        self.labelIPAddress.setGeometry(QtCore.QRect(21, 54, 97, 16))
        self.labelIPAddress.setObjectName("labelIPAddress")
        self.labelBinaryMask = QtWidgets.QLabel(self.groupBoxNetmask)
        self.labelBinaryMask.setGeometry(QtCore.QRect(21, 114, 73, 16))
        self.labelBinaryMask.setObjectName("labelBinaryMask")
        self.lineEditBinaryMask = QtWidgets.QLineEdit(self.groupBoxNetmask)
        self.lineEditBinaryMask.setGeometry(QtCore.QRect(124, 114, 221, 22))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEditBinaryMask.setFont(font)
        self.lineEditBinaryMask.setReadOnly(True)
        self.lineEditBinaryMask.setObjectName("lineEditBinaryMask")
        self.lineEditNWClass = QtWidgets.QLineEdit(self.groupBoxNetmask)
        self.lineEditNWClass.setGeometry(QtCore.QRect(124, 24, 41, 22))
        self.lineEditNWClass.setReadOnly(True)
        self.lineEditNWClass.setObjectName("lineEditNWClass")
        self.labelSubnetMask = QtWidgets.QLabel(self.groupBoxNetmask)
        self.labelSubnetMask.setGeometry(QtCore.QRect(21, 84, 77, 16))
        self.labelSubnetMask.setObjectName("labelSubnetMask")
        self.lineEditSubnetMask = QtWidgets.QLineEdit(self.groupBoxNetmask)
        self.lineEditSubnetMask.setGeometry(QtCore.QRect(124, 84, 221, 22))
        self.lineEditSubnetMask.setReadOnly(True)
        self.lineEditSubnetMask.setObjectName("lineEditSubnetMask")
        self.pushButtonCalculate = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonCalculate.setGeometry(QtCore.QRect(620, 360, 71, 24))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.pushButtonCalculate.setFont(font)
        self.pushButtonCalculate.setObjectName("pushButtonCalculate")
        self.pushButtonReset = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonReset.setGeometry(QtCore.QRect(540, 360, 71, 24))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.pushButtonReset.setFont(font)
        self.pushButtonReset.setObjectName("pushButtonReset")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 717, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuTools = QtWidgets.QMenu(self.menubar)
        self.menuTools.setObjectName("menuTools")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSave_as = QtWidgets.QAction(MainWindow)
        self.actionSave_as.setObjectName("actionSave_as")
        self.actionCtrl_O = QtWidgets.QAction(MainWindow)
        self.actionCtrl_O.setObjectName("actionCtrl_O")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionCalculate = QtWidgets.QAction(MainWindow)
        self.actionCalculate.setObjectName("actionCalculate")
        self.actionClear = QtWidgets.QAction(MainWindow)
        self.actionClear.setObjectName("actionClear")
        self.actionLoad_file = QtWidgets.QAction(MainWindow)
        self.actionLoad_file.setObjectName("actionLoad_file")
        self.actionOpenFile = QtWidgets.QAction(MainWindow)
        self.actionOpenFile.setObjectName("actionOpenFile")
        self.menuFile.addAction(self.actionOpenFile)
        self.menuFile.addAction(self.actionSave_as)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuTools.addAction(self.actionCalculate)
        self.menuTools.addAction(self.actionClear)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Subnet Calculator"))
        self.groupBoxNWInfo.setTitle(_translate("MainWindow", "Network Infomation"))
        self.labelNWAddress.setText(_translate("MainWindow", "Network Address:        "))
        self.labelNumHost.setText(_translate("MainWindow", "# of Hosts per Subnet: "))
        self.labelSbSize.setText(_translate("MainWindow", "Calculated Subnet Size:"))
        self.groupBoxIPRange.setTitle(_translate("MainWindow", "List of IP Ranges"))
        self.groupBoxAddressInfo.setTitle(_translate("MainWindow", "Address Infomation"))
        self.labelDecimalOctets.setText(_translate("MainWindow", "Decimal Octets: "))
        self.labelDecimalAddress.setText(_translate("MainWindow", "Decimal Address: "))
        self.labelBinaryOctets.setText(_translate("MainWindow", "Binary Octets:"))
        self.labelHexOctets.setText(_translate("MainWindow", "Hex Octests: "))
        self.groupBoxNetmask.setTitle(_translate("MainWindow", "Netmask Infomation"))
        self.labelNumSubnet.setText(_translate("MainWindow", "# of Subnets:"))
        self.labelNWClass.setText(_translate("MainWindow", "Network Class: "))
        self.labelIPAddress.setText(_translate("MainWindow", "# of IP Address: "))
        self.labelBinaryMask.setText(_translate("MainWindow", "Binary Mask"))
        self.labelSubnetMask.setText(_translate("MainWindow", "Subnet Mask"))
        self.pushButtonCalculate.setText(_translate("MainWindow", "Calculate"))
        self.pushButtonReset.setText(_translate("MainWindow", "Reset"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuTools.setTitle(_translate("MainWindow", "Tools"))
        self.actionSave_as.setText(_translate("MainWindow", "Save as...    Ctrl+S"))
        self.actionSave_as.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionCtrl_O.setText(_translate("MainWindow", "Ctrl +O"))
        self.actionExit.setText(_translate("MainWindow", "Exit              Ctrl+X"))
        self.actionExit.setShortcut(_translate("MainWindow", "Ctrl+X"))
        self.actionCalculate.setText(_translate("MainWindow", "Calculate    Ctrl+Alt+C"))
        self.actionCalculate.setShortcut(_translate("MainWindow", "Ctrl+Alt+C"))
        self.actionClear.setText(_translate("MainWindow", "Clear           Ctrl+Del"))
        self.actionClear.setShortcut(_translate("MainWindow", "Ctrl+Del"))
        self.actionLoad_file.setText(_translate("MainWindow", "Load file"))
        self.actionOpenFile.setText(_translate("MainWindow", "Open...       Ctrl+O"))
        self.actionOpenFile.setShortcut(_translate("MainWindow", "Ctrl+O"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

